server:
  port: 8081
file:
  directory: photos
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/cars
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

datasourc:
  url: ${spring.datasource.url}
  username: ${spring.datasource.username}
  password: ${spring.datasource.password}
